version: '3'
services:
  cursor-api:
    image: waitkafuka/cursor-api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CURSOR_CHECKSUM=${CURSOR_CHECKSUM}
    volumes:
      - ./logs:/app/logs
    restart: always 